### ISSUE TITLE
Es fehlt eine Lizenz für den Quellcode

### ISSUE THREAD

**Issue by keimlink** [okfde/ris-scraper#4]
Ich habe keine Lizenz für den Quellcode finden können. Es wäre toll wenn eine möglichst freie Lizenz gewählt werden könnte, damit der Quellcode von anderen ebenfalls weiterverwendet werden kann.

**Comment by pudo** [comment]
+1, sehr wichtig. Das Originalprojekt von Marian steht unter MIT, wäre doch auch hier gut!

**Comment by the-infinity** [comment]
Nicht ganz: das Projekt hat seit jeher keine Lizenz: https://github.com/marians/scrape-a-ris *g
Gemeint ist aber dieselbe Lizenz wie in ris-web. Habe die nun auch hier hinzugefügt: https://github.com/okfde/ris-scraper/commit/a7375055d150ae0e54a876f832f86ea3845a84e3

**Comment by pudo** [comment]
Ah, sorry. Hatte hier nachgeschaut: https://github.com/marians/cologne-ris-scraper#unter-welcher-lizenz-steht-der-quellcode

**Comment by keimlink** [comment]
Klasse, vielen Dank!

Gibt es einen Grund dafür, dass ihr eine eigene "MIT-artige Lizenz" und nicht eine von der [OSI anerkannte Lizenz](http://opensource.org/licenses) benutzt?

**Comment by the-infinity** [comment]
Gute Frage, nächste Frage. Das habe ich von Marian einfach übernommen. Am ehesten scheint das ja eine BSD-Lizenz zu sein, oder? Weil die Lizenz ist ja letztlich "Lass den Namen als Autor drin, aber sonst kannst du machen was du willst". Siehe http://opensource.org/licenses/BSD-3-Clause

**Comment by keimlink** [comment]
Genau, ich benutze wenn möglich auch immer die BSD-3-Clause Lizenz.

Die Verwendung einer von der OSI anerkannten Lizenz macht es für andere einfacher zu verstehen was erlaubt ist, da die Lizenz ja schon bekannt ist bzw. leicht zu recherchieren ist, was erlaubt ist. Bei einer eigenen Lizenz muss das erst vor der Weiterverwendung recherchiert werden. Außerdem kann eine eigene Lizenz, wenn sie nicht von einer Juristin geprüft wurde, Fehler enthalten und damit ungültig sein.

Ich würde mich freuen wenn ihr beide Projekte unter der BSD-3-Clause Lizenz lizensieren würdet.

**Comment by akuckartz** [comment]
Ein Problem ist, dass sich selbst (scheinbar) kleine textuelle Abweichungen zu anerkannten Lizenzen _potentiell_ rechtlich auswirken _können_.

Ein weiterer Punkt ist, dass die deutsche Sprache für eine internationale Verwendung eher hinderlich ist. Die OSI hat zudem meines Wissens keine einzige in deutscher Sprache formulierte Lizenz anerkannt, sondern setzt die englische Sprache voraus. Die einzige Ausnahme dürften im Ergebnis die Sprachversionen der EUPL sein, da diese in der EU gleichermassen rechtlich verbindlich sind.

**Comment by the-infinity** [comment]
Update: Marian hat gerade zugestimmt, das Projekt in BSD 3 Clause zu ändern: http://opensource.org/licenses/BSD-3-Clause . Kommt beim nächstbesten Update mit rein. :)

**Comment by akuckartz** [comment]
:+1:

**Comment by keimlink** [comment]
Yay! 😀
