### ISSUE TITLE
"No module named mechanize"

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-scraper#7]
Ich arbeite https://github.com/okfde/ris-scraper/wiki/Benutzung durch. Das Ergebnis von

```
$ python main.py
```

ist

```
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    from risscraper.scrapersessionnet import ScraperSessionNet
  File "/srv/www/ris-scraper/risscraper/scrapersessionnet.py", line 26, in <module>
    import mechanize
ImportError: No module named mechanize
```

**Comment by the-infinity** [comment]
Dann hast du die Installationsanleitung nicht komplett befolgt. Dort wird mechanize in das Virtual Enviroment installiert über:

> pip install -r requirements.txt

**Comment by akuckartz** [comment]
Doch, den Befehl hatte ich (mit vorangestelltem "sudo") ausgeführt. Das hat auch diese Spur bzgl. `mechanize` hinterlassen:

```
Requirement already satisfied (use --upgrade to upgrade): mechanize in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
```

Habe schon gesehen, dass es im Web diverse Hinweise auf ein wahrscheinliches Pfad-Problem gibt.

**Comment by the-infinity** [comment]
Dann bist du nicht im Virtual Enviroment drin. Die Anleitung ist keine Copy Paste Anleitung, sondern zeigt auf, was ungefähr zu tun ist. Man wechselt da ja auch zwischen root und Systemuser mehrfach hin und her, ohne dass das explizit gesagt wird. Für eine vollständiges Setup würde ich den Installer empfehlen, alleine, um ein Interface für die Config-Files zu haben, welche in der MongoDB liegen.

**Comment by akuckartz** [comment]
Laut Prompt bin ich im Virtual Environment. Mit "Installer" meinst du den des Parallel-Projekts `ris-web`, richtig?

**Comment by akuckartz** [comment]
Ursache des Problems war anscheinend das `sudo`. Das hatte ich verwendet, weil ich beim ersten Aufruf des `pip`-Befehls ohne `sudo` ein Rechteproblem hatte...

**Comment by the-infinity** [comment]
Man muss bei dem System schon recht genau auf die Rechte achten, yep ;)
Und yep, der Installer von ris-web installiert ris-scraper gleich mit. Die beiden Projekte nutzen eine gemeinsame zentrale Konfiguration.

**Comment by akuckartz** [comment]
Letzter Stand:

```
$ pip install -r requirements.txt
```

ergab nach einer Weile dies:

```
running install_lib
creating /srv/www/ris-scraper/venv/lib/python2.7/site-packages/lxml
error: could not create '/srv/www/ris-scraper/venv/lib/python2.7/site-packages/lxml': Permission denied
```

Eventuell fange ich noch mal von vorne an. Ubuntu verwendet ich nicht,sondern Debian, der Installer ist deshalb vermutlich keine Alternative.

**Comment by the-infinity** [comment]
Yep, da hast du die Ordner nicht mit Nutzerrechten erstellt, woraufhin du nun ein Problem mit den Schreibrechten hast.
Ich würde, wenn du bislang weniger Erfahrung mit Linux hast, eine Ubuntu VM nutzen. Weite Teile dessen, was hier steht, ist eher konzeptionell als eine Schritt für Schritt Anleitung, weswegen wir ja gerade den Installer entwickelt haben.

**Comment by akuckartz** [comment]
Sind eher neue Erfahrungen mit der Python-Welt. Den Installer schaue ich mir genauer an, da ist jedenfalls eindeutig, was jeweils zu tun ist ;-)

**Comment by akuckartz** [comment]
Ich habe nun das Installations-Skript von `ris-web` leicht lokal angepasst und erfolgreich ausgeführt.

Die Wiki-Seite für die Installation von `ris-scraper` habe ich basierend auf den Erfahrungen etwas verbessert.

**Comment by akuckartz** [comment]
Nachtrag: Ich habe `ris-scraper` mit dem Installationsscript von `ris-web` installiert und dafür nur etwa 15 Minuten manuelle Zeit benötigt. Den Scraper habe ich exemplarisch für ein RIS konfiguriert und für einen Monat Daten scrapen lassen. Es gab dabei keine Probleme.
